### ISSUE TITLE
Assety poza folderema assets?!?!?!

### ISSUE THREAD

**Issue by D-Mielewczyk** [marcelsikorski/ultimate_platformer_experience#2]
Commit [wazny update](https://github.com/marcelsikorski/ultimate_platformer_experience/commit/ad921f0b6759d7c2db47da14f3ea283cc6b4d98b) dodany przez @marcelsikorski dodał pliki **.jpg** do folderu `First Game`. Powinny się znaleźć w `First Game\assets`. Przy okazji przydało by się sprzątnąć assety, które zostały tam wrzucone wraz z inital commitem.

**Comment by marcelsikorski** [comment]
jes ok
